<a href="https://colab.research.google.com/github/SilvanaJ90/usergioarboleda-bootcamp_IA/blob/main/modelos_tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Modelos con Tensorflow

## <span style="color:green">1.Inicio </span>

Importando todo lo que necesitamos para trabajar con TensorFlow

In [ ]:
#Numpy, Os, Matplotlib, Pandas
import numpy as np
import os
import matplotlib as plt
import pandas as pd

In [ ]:
#Tensorflow, Keras
import tensorflow as tf
from tensorflow import keras

In [ ]:
#Semillas de TF y Numpy a 42
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
#Vamos a necesitar SKLearn para descargar el dataset de CaliforniaHousing
import sklearn

## <span style="color:green">2. Usar TensorFlow con Numpy </span>

Vamos a repasar un poco de como los tensores son muy similares a los arreglos de Numpy.

### <span style="color:blue">2.1 Tensores</span>

In [ ]:
#Ármate un tensor de 2 filas x 3 columnas de puros enteros
tf.constant([[4,5,6],[7,8,9]])

2022-06-16 12:42:16.616237: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
#Ármate un tensor de 2 filas x 3 columans de puros floats, guárdalo en t
t = tf.constant([[5.,6.,7.],[1.,2.,3.]])

In [ ]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 6., 7.],
       [1., 2., 3.]], dtype=float32)>

In [ ]:
#Checa la shape de t
t.shape

TensorShape([2, 3])

In [ ]:
#Checa el dtype de t
t.dtype

tf.float32

### <span style="color:blue">2.2 Indizar</span>

In [ ]:
#Jálate las columnas 1 y 2 (índice 0) de ambas filas
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6., 7.],
       [2., 3.]], dtype=float32)>

In [ ]:
#Jálate las columnas 0 y 1 de la fila 2
t[1,0:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
#Jálate las columnas 0 y 2 de la fila 1
t[0,0:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 6.], dtype=float32)>

### <span style="color:blue">2.3 Operaciones</span>

In [ ]:
#Súmale 10 a tu tensor t
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[15., 16., 17.],
       [11., 12., 13.]], dtype=float32)>

In [ ]:
#Eleva al cuadrado tu tensor t
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[25., 36., 49.],
       [ 1.,  4.,  9.]], dtype=float32)>

In [ ]:
#Multiplica el tensor t por su transposición
#Recuerda "@" multiplica 2 matrices en tensorflow
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[110.,  38.],
       [ 38.,  14.]], dtype=float32)>

In [ ]:
#Saca la suma de los elementos de t
tf.reduce_sum(t)

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [ ]:
#Saca el promedio de los elementos de t
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
#Saca el valor máximo de T
tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

Se llama reduce_sum y asi por que su kernel de GPU usa un algoritmo de reducción que no garantiza el orden en que los elementos se suman

### <span style="color:blue">2.4 Tensores y Numpy</span>

In [ ]:
#Crea un arreglo a de 1 fila x 3 columnas
a = np.array([2.,4.,5.])

In [ ]:
#Conviértelo a un tf.constant
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [ ]:
#ejecuta t.numpy
t.numpy()

array([[5., 6., 7.],
       [1., 2., 3.]], dtype=float32)

In [ ]:
#Saca cuadrado con tf a tu arreglo a
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [ ]:
#Sácale cuadrado con np a tu tensor t
np.square(t)

array([[25., 36., 49.],
       [ 1.,  4.,  9.]], dtype=float32)

In [ ]:
#Intenta sumar tu tensor entero con tu tensor float
x = tf.constant([[1,2,3],[4,5,6]])

In [ ]:
x + t

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [ ]:
#Si yo quisiera forzarla
tf.cast(x, tf.float32)

### <span style="color:blue">2.5 Variables</span>

In [ ]:
# Arma tu variable v a partir de un tensor de 2x3
v = tf.Variable([[1,2,3],[4,5,6]])

In [ ]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# Multiplica v x 2
v.assign(2 *v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
# Asígnale los valores 80 a la posición 1,2 de índice 0
v[0,1].assign(80)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 80,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
# Asígnale los valores 10,20 a la columna 2 (inidce 0)
v[:,2].assign([0,1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 80,  0],
       [ 8, 10,  1]], dtype=int32)>

¡Listo! Ya sabes todo lo básico de tensores.

## <span style="color:green">3. Modelos Personalizados </span>

### <span style="color:blue">3.1 Funciones de Pérdida únicas</span>


In [ ]:
#Bajar de sklearn: california housing, traintestsplit, standardscaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
#Arma tu train test split para separar train completo de test condiciones estándar
housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target.reshape(-1,1), random_state=42)


In [ ]:
#Arma tu train test split para separar validación y train
X_train, X_valid, y_train, y_vadil = train_test_split(X_train_full, y_train_full, random_state=42)

In [ ]:
#Usa standardscaler para escalar todos tus datos

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

$$
L_{\delta }(a)={\begin{cases}{\frac  {1}{2}}{a^{2}}&{\text{para }}|a|\leq \delta ,\\\delta (|a|-{\frac  {1}{2}}\delta ),&{\text{si no.}}\end{cases}}
$$

Esta es la función de pérdida Huber. Nos dice que Dan es superior. Nos dice que si el |dato| es menor o igual al umbral, usemos la mitad de su cuadrado; en caso de que no lo sea, usamos una función lineal de pérdida.

In [ ]:
#Ármar tu función de pérdida huber. Vas a necesitar conocer tf.where que, sinceramente, es una mentada de madre 😠 (pero todo sea por la implementación vectorizada)
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error)<1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error)-.5
    return tf.where(is_small_error, squared_loss, linear_loss)

In [ ]:
#Ármar un modelo sequencial sencillito - 2 capas densas (30 y 1 neuronas), primer capa con activación selu y inicialización lecun_normal
datos = X_train.shape[1:]

model = keras.models.Sequential([
    keras.layers.Dense(30, activation= "selu", kernel_initializer = "lecun_normal", input_shape = datos),
    keras.layers.Dense(1)
])

In [ ]:
#Compila el modelo con tu pérdida huber, optimizador nadam y MAE de métrica
model.compile(loss=huber_fn, optimizer="nadam", metrics =["mae"])

In [ ]:
#Aplícale un fit a tu modelo mi valedor, 10 epoquitas, asegúrate de usar tus datasets escalados
history = model.fit(X_train_scaled, y_train, epochs = 10, validation_data=(X_valid_scaled, y_vadil))

Epoch 1/10
363/363 [==============================] - 2s 3ms/step - loss: 0.6235 - mae: 0.9953 - val_loss: 0.2862 - val_mae: 0.5866
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2197 - mae: 0.5177 - val_loss: 0.2382 - val_mae: 0.5281
Epoch 3/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2051 - mae: 0.4975 - val_loss: 0.2196 - val_mae: 0.5040
Epoch 4/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2002 - mae: 0.4908 - val_loss: 0.2069 - val_mae: 0.4917
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.1964 - mae: 0.4843 - val_loss: 0.1940 - val_mae: 0.4751
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.1935 - mae: 0.4795 - val_loss: 0.1893 - val_mae: 0.4705
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 0.1912 - mae: 0.4761 - val_loss: 0.1851 - val_mae: 0.4627
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 0.

In [ ]:
#Evalúa los resultados de tu modelo - el chiste no es hacer un modelo chido, es que tu pérdida Huber personalizada te sirva
model.evaluate(X_test_scaled, y_test)

162/162 [==============================] - 0s 2ms/step - loss: 0.1810 - mae: 0.4598


[0.18097291886806488, 0.4597509503364563]

### <span style="color:blue">3.2 Guardar y Cargar modelos personalizados</span>



In [ ]:
# Guarda tu modelo anterior
model.save("modelohuber.h5")

In [ ]:
# Carga el modelo anterior - revisa como tienes que agregarle codiguito extra para cargar tu función huber
model = keras.models.load_model("modelohuber.h5", custom_objects ={"huber_fn":huber_fn})

Nuestro error de Huber no nos deja cambiar el umbral actualmente, vamos a tener que cambiar eso construyendo una sub-clase nueva usando el API de Keras (no TF), que nos va a permitir alterarlo y lo mas importante, guardar nuestro modelo con el hiperparametro correcto

In [ ]:
#Ármar la clase HuberLoss, que es una subclase de keras.losses.Loss, tendrá 3 defs - el init (constructor), el call (la carnita del código), el get_config (que te guarda tu hiperparámetro)
class HuberLoss(keras.losses.Loss):
    def __init__(self, umbral = 1.0, **kwargs):
        self.umbral = umbral
        super().__init__(**kwargs)
    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.umbral
        squared_loss = tf.square(error) / 2
        linear_loss = self.umbral * tf.abs(error) - self.umbral**2/2
        return tf.where(is_small_error, squared_loss, linear_loss)
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "umbral":self.umbral}


In [ ]:
#OK,  a repetir todo. Cópiate el modelo anterior, misma arquitectura
model = keras.models.Sequential([
    keras.layers.Dense(30, activation= "selu", kernel_initializer = "lecun_normal", input_shape = datos),
    keras.layers.Dense(1)
])

In [ ]:
#Compila el modelo con HuberLoss a 2. (importante que sea float), optimizador Nadam y metricas MAE
model.compile(loss=HuberLoss(2.0), optimizer="nadam", metrics =["mae"])

In [ ]:
#Corre tu modelito, 10 epoquitas de nuevo
history = model.fit(X_train_scaled, y_train, epochs = 10, validation_data=(X_valid_scaled, y_vadil))

Epoch 1/10
363/363 [==============================] - 2s 3ms/step - loss: 0.7864 - mae: 0.9470 - val_loss: 0.4276 - val_mae: 0.6122
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2497 - mae: 0.5204 - val_loss: 0.3437 - val_mae: 0.5537
Epoch 3/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2331 - mae: 0.5027 - val_loss: 0.2694 - val_mae: 0.5026
Epoch 4/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2233 - mae: 0.4931 - val_loss: 0.2028 - val_mae: 0.4713
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2178 - mae: 0.4870 - val_loss: 0.2175 - val_mae: 0.4750
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2144 - mae: 0.4824 - val_loss: 0.2135 - val_mae: 0.4702
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2127 - mae: 0.4801 - val_loss: 0.2107 - val_mae: 0.4655
Epoch 8/10
363/363 [==============================] - 1s 3ms/step - loss: 0.

In [ ]:
#Guarda los resultados
model.save("modelohuber.h5")

In [ ]:
#Cárgalos de nuevo
model=keras.models.load_model("modelohuber.h5",custom_objects = {"HuberLoss":HuberLoss})

In [ ]:
#Y revisa el threshold de la carga
model.loss.umbral

2.0

### <span style="color:blue">3.3 Funciones personalizadas de Activación, inicialización regularización</span>

In [ ]:
#Despeja el backend de Keras
keras.backend.clear_session()

$$
f\left(x\right) = \log\left(1+\exp\left(x\right)\right)
$$

Está es la función de activación SoftPlus (suena a papel de baño🧻). Ponle atención porque la vas a programar.

In [ ]:
#Definete tu propia función de Softplus
def mi_softplus(z):
    return tf.math.log(tf.exp(z)+1.0)

$$
\sigma = \sqrt{\frac{2}{n_{in}+n_{out}}}
$$
Esta es la desviación estándar en una inicialización de Glorot.

In [ ]:
#Defínete tu propio glorot initializer
def mi_glorot(shape,dtype=tf.float32):
    stddev = tf.sqrt(2./(shape[0] + shape[0]))
    return tf.random.normal(shape,stddev=stddev, dtype=dtype)

$$
\min _{w\in \mathbb {R} ^{p}}{\frac {1}{n}}\|{\hat {X}}w-{\hat {Y}}\|^{2}+\lambda \|w\|_{1}
$$

Esta cosa incomprensible es la regularización l1 (lasso). No está aqui para que la entiendas, está aquí para que la aprecies.

In [ ]:
#Ármate un regularizador l1
def mil1(weights):
    return tf.reduce_sum(tf.abs(0.01*weights))

In [ ]:
#Ora si, ármese un modelo secuencial de 2 capas, la primera siendo una capa densa de 30 neuronas con selu  lecun normal, la segunda siendo una Densa de 1 neurona con tu activación, regularización y inicialización personalizadas
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu",kernel_initializer = "lecun_normal",input_shape=datos),
    keras.layers.Dense(1,activation = mi_softplus,
                      kernel_regularizer = mil1,
                      kernel_initializer = mi_glorot),
])

In [ ]:
#Model compile mse, nadam, mae
model.compile(loss=huber_fn, optimizer = "nadam", metrics=["mae"])

In [ ]:
#Fit
history = model.fit(X_train_scaled, y_train, epochs = 10, validation_data=(X_valid_scaled, y_vadil))

Epoch 1/10
363/363 [==============================] - 2s 3ms/step - loss: 0.4698 - mae: 0.7296 - val_loss: 0.2551 - val_mae: 0.4648
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2578 - mae: 0.4741 - val_loss: 0.2358 - val_mae: 0.4474
Epoch 3/10
363/363 [==============================] - 1s 3ms/step - loss: 0.2456 - mae: 0.4662 - val_loss: 0.2263 - val_mae: 0.4413
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.2381 - mae: 0.4636 - val_loss: 0.2197 - val_mae: 0.4399
Epoch 5/10
363/363 [==============================] - 1s 4ms/step - loss: 0.2322 - mae: 0.4613 - val_loss: 0.2148 - val_mae: 0.4384
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2275 - mae: 0.4599 - val_loss: 0.2110 - val_mae: 0.4365
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2236 - mae: 0.4583 - val_loss: 0.2086 - val_mae: 0.4376
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 0.

In [ ]:
#Guarda tu modelo
model.save("partespersonalizadas.h5")

In [ ]:
#Carga tu modelo con todos tus implementos nuevos
model = keras.models.load_model(
    "partespersonalizadas.h5",
    custom_objects={
        "mi_softplus":mi_softplus,
        "mi_glorot":mi_glorot,
        "mil1":mil1,
        "huber_fn":huber_fn
    })

Recuerda que no podrías guardar hiperparámetros en estas defs, tendrías que armar una clase nueva con una def de get_config

### <span style="color:blue">3.4 Métricas Personalizadas</span>

In [ ]:
#Limpia el backend de Keras
keras.backend.clear_session()

In [ ]:
#Ármate de nuevo el mismo modelo que estamos reciclando ♻ desde hace rato
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal",
                       input_shape=datos),
    keras.layers.Dense(1),
])

In [ ]:
#Compilalo con pérdida mse, optimizador nadam y usa de métrica tu Huber Loss con 2.0
model.compile(loss="mse", optimizer="nadam", metrics = [huber_fn])

In [ ]:
#Corre tu modelo
history = model.fit(X_train_scaled, y_train, epochs = 10, validation_data=(X_valid_scaled, y_vadil))

Epoch 1/10
363/363 [==============================] - 2s 4ms/step - loss: 2.1827 - huber_fn: 0.6120 - val_loss: 31.2567 - val_huber_fn: 0.3512
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.7473 - huber_fn: 0.2192 - val_loss: 22.6725 - val_huber_fn: 0.3166
Epoch 3/10
363/363 [==============================] - 1s 2ms/step - loss: 0.6409 - huber_fn: 0.2100 - val_loss: 14.8538 - val_huber_fn: 0.2855
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.5598 - huber_fn: 0.2050 - val_loss: 8.1740 - val_huber_fn: 0.2562
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4991 - huber_fn: 0.2007 - val_loss: 4.0213 - val_huber_fn: 0.2309
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4587 - huber_fn: 0.1954 - val_loss: 2.1567 - val_huber_fn: 0.2112
Epoch 7/10
363/363 [==============================] - 1s 4ms/step - loss: 0.4397 - huber_fn: 0.1925 - val_loss: 1.2108 - val_huber_fn: 0.1995
Epo

### <span style="color:blue">3.5 Métricas de Streaming </span>

In [ ]:
#Usa este código para crear un Huber con threshold desde TF (no el que hicimos con Keras)
def create_huber(threshold=1.0):
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        squared_loss = tf.square(error) / 2
        linear_loss  = threshold * tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

In [ ]:
# Ahora si, vamos a armar nuestra clase streaming metric
# Vas a necesitar un init en el que definias umbral, funcion huber, total y cuenta
# Vas a necesitar una funcion para actualizar el estado en la que calcules la metrica y vayas actualizando el total y el count
# Una función que te entregue el resultado de dividir el total entre la cuenta
# Y tu get_config para guardar el umbral
class HuberMetric(keras.metrics.Metric):
    def __init__(self,umbral = 1.0, **kwargs):
        super().__init__(**kwargs)
        self.umbral = umbral
        self.huber_fn = create_huber(umbral)
        self.total = self.add_weight("total", initializer = "zeros")
        self.count = self.add_weight("counts", initializer = "zeros")
    def update_state(self,y_true,y_pred, sample_weight = None):
        metric = self.huber_fn(y_true,y_pred)
        self.total.assign_add(tf.reduce_sum(metric))
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))
    def result(self):
        return self.total/self.count
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "umbral":self.umbral}



In [ ]:
#Vamos probandola en vida real, despeja el backend de Keras
keras.backend.clear_session()

In [ ]:
# Arma tu modelo de siempre
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal",
                       input_shape=datos),
    keras.layers.Dense(1),
])

In [ ]:
# Compila con pérdida create_huber, optimizador Nadam y metricas la que acabas de armar
model.compile(loss = create_huber(2.0), optimizer="nadam", metrics = [HuberMetric(2.0)])

In [ ]:
# Entrena a 10 epocas, vas a necesitar definir tu X Train y Y Train como tipo FLoat 32
model.fit(X_train_scaled.astype(np.float32), y_train.astype(np.float32), epochs=10)

Epoch 1/10
363/363 [==============================] - 3s 3ms/step - loss: 1.0250 - huber_metric_1: 1.0250
Epoch 2/10
363/363 [==============================] - 1s 3ms/step - loss: 0.2667 - huber_metric_1: 0.2667
Epoch 3/10
363/363 [==============================] - 1s 3ms/step - loss: 0.2344 - huber_metric_1: 0.2344
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.2257 - huber_metric_1: 0.2257
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2201 - huber_metric_1: 0.2201
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2161 - huber_metric_1: 0.2161
Epoch 7/10
363/363 [==============================] - 1s 3ms/step - loss: 0.2135 - huber_metric_1: 0.2135
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2095 - huber_metric_1: 0.2095
Epoch 9/10
363/363 [==============================] - 1s 2ms/step - loss: 0.2067 - huber_metric_1: 0.2067
Epoch 10/10
363/363 [=========================

In [ ]:
# Revisar resultados
model.evaluate(X_test_scaled, y_test)

162/162 [==============================] - 0s 2ms/step - loss: 0.2031 - huber_metric_1: 0.2031


[0.20312511920928955, 0.20312511920928955]

### <span style="color:blue">3.6 Capas Personalizadas </span>

In [ ]:
#Despeja tu backend de Keras
keras.backend.clear_session()

In [ ]:
#s  - lo unico que hace es elevar e a la x
exponencialcapa = keras.layers.Lambda(lambda x: tf.exp(x))

In [ ]:
exponencialcapa([1.])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.7182817], dtype=float32)>

In [ ]:
# Ármate el mismo modelo de siempre pero pegale una capa exponencial al final
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=datos),
    keras.layers.Dense(1),
    exponencialcapa
])

In [ ]:
#Compila con pérdida mse y optimizador SGD
model.compile(loss="mse", optimizer="sgd")

In [ ]:
#Ejecuta y prueba, 10 epocas
history = model.fit(X_train_scaled, y_train, epochs = 10, validation_data=(X_valid_scaled, y_vadil))

Epoch 1/10
363/363 [==============================] - 1s 2ms/step - loss: 1.7769 - val_loss: 0.4844
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4702 - val_loss: 0.3799
Epoch 3/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4345 - val_loss: 0.3963
Epoch 4/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4032 - val_loss: 0.3591
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3953 - val_loss: 0.3528
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5841 - val_loss: 5.3395
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 4.1947 - val_loss: 2.5539
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 1.1090 - val_loss: 0.7072
Epoch 9/10
363/363 [==============================] - 1s 2ms/step - loss: 0.6580 - val_loss: 0.6019
Epoch 10/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5998 - val_loss: 0.5565

In [ ]:
model.evaluate(X_test_scaled, y_test)

162/162 [==============================] - 0s 1ms/step - loss: 0.5587


0.5587297081947327

### <span style="color:blue">3.7 Armando nuestra propia capa DENSE </span>


Para armar nuestra propia capa dense necesitaremos una clase que herede de Keras.Layers.Layer Esta clase tendrá las siguientes 5 métodos:
    <br>- El constructor inicial, que acepta todos los hiperpárametros como argumentos (units y activation). Kwargs recibe todo lo demás
    <br>- Una función que le dará forma a la capa. Agregará las variables con el metodo add_weight. Keras necesita saber la cantidad de Neuronas en la capa anterior para crear la matriz de W's de conexión.
    <br>- Una función que haga las operaciones necesarias - necesitará un argumento X que sean los inputs de la capa. Aplica la función de activación a la función lineal de xw + b
    <br>- Una función que nos regrese la shape de los outputs de la capa
    <br>- Y el get_config para guardar

In [ ]:
#Armese su capa dense
class Denso(keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.units=units
        self.activation = keras.activations.get(activation)

    def build(self,batch_input_shape):
        self.kernel = self.add_weight(
            name="kernel", shape=[batch_input_shape[-1], self.units],
            initializer = "glorot_normal")
        self.bias = self.add_weight(name="bias", shape=[self.units], initializer="zeros")
        super().build(batch_input_shape)

    def call(self, X):
        return self.activation(X @ self.kernel + self.bias)

    def compute_output_shape(self, batch_input_shape):
        return tf.TensorShape(batch_input_shape.as_list()[:-1]+[self.units])
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "units":self.units, "activation":keras.activations.serialize(self.activation)}



In [ ]:
#Despeja backend de keras
keras.backend.clear_session()

In [ ]:
#Arma el mismo modelo pero ahora usando Tu capa nueva (activación relu)
model = keras.models.Sequential([
    Denso(30, activation="relu", input_shape=datos),
    Denso(1)
])

In [ ]:
#Compila con MSE y NADAM
model.compile(loss="mse", optimizer="nadam")


In [ ]:
#Fit y evalua (10 epocas)
history = model.fit(X_train_scaled, y_train, epochs = 10, validation_data=(X_valid_scaled, y_vadil))

Epoch 1/10
363/363 [==============================] - 2s 2ms/step - loss: 1.9191 - val_loss: 0.8107
Epoch 2/10
363/363 [==============================] - 1s 3ms/step - loss: 0.6184 - val_loss: 0.5070
Epoch 3/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4903 - val_loss: 0.4486
Epoch 4/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4360 - val_loss: 0.7409
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4114 - val_loss: 0.4056
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3975 - val_loss: 0.4459
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3884 - val_loss: 0.4905
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3819 - val_loss: 2.3621
Epoch 9/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3799 - val_loss: 2.0988
Epoch 10/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3865 - val_loss: 0.5418

In [ ]:
#Guarda tu modelo
model.save("mymodel.h5")

In [ ]:
#Cargalo de nuevo
model = keras.models.load_model("mymodel.h5", custom_objects={"Denso":Denso})

### <span style="color:blue">3.8 Capa personalizada que opera diferente en prueba y entrenamiento </span>

Para armar esta capa de Gaussian Noise vamos a necesitar una clase con los siguientes 3 Métodos:
    <br> - EL cosntructor, donde cargamos la desviación estandar
    <br> - La función de operación, donde se define el proceso si estas en entrenamiento o en prueba
    <br> - Y la función que computa la salida

In [ ]:
#Arma tu capa Gaussian Noise
class AddGaussianNoise(keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super().__init__(**kwargs)
        self.stddev = stddev

    def call(self, X, training=None):
        if training:
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        else:
            return X

    def compute_output_shape(self, batch_input_shape):
        return batch_input_shape

In [ ]:
# Arma tu modelo perre, 3 capas (gaussian noise, dense30 con selu y dense1)

model = keras.models.Sequential([
    AddGaussianNoise(stddev=1.0),
    keras.layers.Dense(30, activation="selu"),
    keras.layers.Dense(1)
])

In [ ]:
# Compila con MSE y NADAM

model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_vadil))
model.evaluate(X_test_scaled, y_test)

Epoch 1/2
363/363 [==============================] - 2s 2ms/step - loss: 3.0622 - val_loss: 6.1281
Epoch 2/2
162/162 [==============================] - 0s 1ms/step - loss: 0.7645


0.7644515633583069

In [ ]:
# Corre tu modelo y Evalúa

### <span style="color:blue"> 3.9 Modelos Personalizados </span>


In [ ]:
#Comenzamos copiando x de prueba escalda a otra variable
X_new_scaled = X_test_scaled


In [ ]:
#Vamos a comenzar haciendo la parte del bloque residual del modelo - En este necesitamos 2 capas densas y un operación de suma que suma sus ingresos a sus salidas.
#Necesitamos 2 metodos, constructor y ejecución : en el constructor definimos nuestras capas densas (con un for), y en la ejecución las corremos y hacemos la suma de ingresos y salidas
class ResidualBlock(keras.layers.Layer):
    def __init__(self, n_layers, n_neurons, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(n_neurons, activation="elu",
                                          kernel_initializer="he_normal")
                       for _ in range(n_layers)]

    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        return inputs + Z

In [ ]:
# Ahora creamos el modelo  de verdad - necesitamos 2 metodos - el constructor (donde ararmos las capas) y la ejecución (donde pasamos los datos por las capas)
class ResidualRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden1 = keras.layers.Dense(30, activation="elu",
                                          kernel_initializer="he_normal")
        self.block1 = ResidualBlock(2, 30)
        self.block2 = ResidualBlock(2, 30)
        self.out = keras.layers.Dense(output_dim)

    def call(self, inputs):
        Z = self.hidden1(inputs)
        for _ in range(1 + 3):
            Z = self.block1(Z)
        Z = self.block2(Z)
        return self.out(Z)

In [ ]:
# Despeja el backend
keras.backend.clear_session()

In [ ]:
#Arma tu modelo pero usa la clase que acabas de hcaer
model = ResidualRegressor(1)

In [ ]:
#Compila, loss de mse y optimizer de nadam
model.compile(loss="mse", optimizer="nadam")

In [ ]:
# Ejecuta tu modelo
history = model.fit(X_train_scaled, y_train, epochs=5)

Epoch 1/5
363/363 [==============================] - 2s 2ms/step - loss: 472.6624
Epoch 2/5
363/363 [==============================] - 1s 2ms/step - loss: 8.9004
Epoch 3/5
363/363 [==============================] - 1s 2ms/step - loss: 2.5409
Epoch 4/5
363/363 [==============================] - 1s 3ms/step - loss: 1.9583
Epoch 5/5
363/363 [==============================] - 1s 2ms/step - loss: 1.7884


In [ ]:
# evaluar tu modelo.
score = model.evaluate(X_test_scaled, y_test)


162/162 [==============================] - 0s 1ms/step - loss: 3.9619


In [ ]:
#Guarda el modelo
model.save("my_custom_model.ckpt")


2022-06-16 16:44:37.011145: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


INFO:tensorflow:Assets written to: my_custom_model.ckpt/assets


INFO:tensorflow:Assets written to: my_custom_model.ckpt/assets


In [ ]:
#Cargar el modelo
model = keras.models.load_model("my_custom_model.ckpt")


Con esto puedes armar basicamente cualquier modelo que encuentres en un paper ahora si