<a href="https://colab.research.google.com/github/SilvanaJ90/usergioarboleda-bootcamp_IA/blob/main/Tutorial_Procesar_Datos_Tensor_Flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cargar y Preprocesar Datos con TensorFlow


In [ ]:
#numpy y OS
import numpy as np
import os

In [ ]:
# Scikit Learn
import sklearn

In [ ]:
# Tensorflow y Keras
import tensorflow as tf
from tensorflow import keras

In [ ]:
#Semillas a 42
np.random.seed(42)
tf.random.set_seed(42)

## <span style="color:green">1.Datasets Tensorflow </span>

In [ ]:
# Población(en miles) de los 17 estados con más personas de México.
Mexico = [16992,9209,8348,8062,6583,6116,5784,5543,4748,4132,3769,3741,3540,3527,3146,3082,3026]

In [ ]:
#Ármate un dataset desde la lista anterior
dataset = tf.data.Dataset.from_tensor_slices(Mexico)

2022-06-09 19:21:10.262257: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
#Itera sobre el dataset
for item in dataset:
    print(item)

tf.Tensor(16992, shape=(), dtype=int32)
tf.Tensor(9209, shape=(), dtype=int32)
tf.Tensor(8348, shape=(), dtype=int32)
tf.Tensor(8062, shape=(), dtype=int32)
tf.Tensor(6583, shape=(), dtype=int32)
tf.Tensor(6116, shape=(), dtype=int32)
tf.Tensor(5784, shape=(), dtype=int32)
tf.Tensor(5543, shape=(), dtype=int32)
tf.Tensor(4748, shape=(), dtype=int32)
tf.Tensor(4132, shape=(), dtype=int32)
tf.Tensor(3769, shape=(), dtype=int32)
tf.Tensor(3741, shape=(), dtype=int32)
tf.Tensor(3540, shape=(), dtype=int32)
tf.Tensor(3527, shape=(), dtype=int32)
tf.Tensor(3146, shape=(), dtype=int32)
tf.Tensor(3082, shape=(), dtype=int32)
tf.Tensor(3026, shape=(), dtype=int32)


### <span style="color:blue">1.1 Encadenar Transformaciones</span>

In [ ]:
#Repite el dataset 2 veces y muéstralo en baches de 10, muestra tus resultados
dataset = dataset.repeat(2).batch(10)

In [ ]:
#Visualiza el resultado
for item in dataset:
    print(item)

tf.Tensor([16992  9209  8348  8062  6583  6116  5784  5543  4748  4132], shape=(10,), dtype=int32)
tf.Tensor([ 3769  3741  3540  3527  3146  3082  3026 16992  9209  8348], shape=(10,), dtype=int32)
tf.Tensor([8062 6583 6116 5784 5543 4748 4132 3769 3741 3540], shape=(10,), dtype=int32)
tf.Tensor([3527 3146 3082 3026], shape=(4,), dtype=int32)


In [ ]:
#Usa map y lambada para multiplicar todas las poblaciones por 1000
dataset = dataset.map(lambda x: x*2)

In [ ]:
#Imprime resultados
for item in dataset:
    print(item)

tf.Tensor([33984 18418 16696 16124 13166 12232 11568 11086  9496  8264], shape=(10,), dtype=int32)
tf.Tensor([ 7538  7482  7080  7054  6292  6164  6052 33984 18418 16696], shape=(10,), dtype=int32)
tf.Tensor([16124 13166 12232 11568 11086  9496  8264  7538  7482  7080], shape=(10,), dtype=int32)
tf.Tensor([7054 6292 6164 6052], shape=(4,), dtype=int32)


In [ ]:
#Convierte cada dato a su propio tensor (en vez de tener baches de 10 tensores)
dataset = dataset.unbatch()

In [ ]:
for item in dataset:
    print(item)

tf.Tensor(33984, shape=(), dtype=int32)
tf.Tensor(18418, shape=(), dtype=int32)
tf.Tensor(16696, shape=(), dtype=int32)
tf.Tensor(16124, shape=(), dtype=int32)
tf.Tensor(13166, shape=(), dtype=int32)
tf.Tensor(12232, shape=(), dtype=int32)
tf.Tensor(11568, shape=(), dtype=int32)
tf.Tensor(11086, shape=(), dtype=int32)
tf.Tensor(9496, shape=(), dtype=int32)
tf.Tensor(8264, shape=(), dtype=int32)
tf.Tensor(7538, shape=(), dtype=int32)
tf.Tensor(7482, shape=(), dtype=int32)
tf.Tensor(7080, shape=(), dtype=int32)
tf.Tensor(7054, shape=(), dtype=int32)
tf.Tensor(6292, shape=(), dtype=int32)
tf.Tensor(6164, shape=(), dtype=int32)
tf.Tensor(6052, shape=(), dtype=int32)
tf.Tensor(33984, shape=(), dtype=int32)
tf.Tensor(18418, shape=(), dtype=int32)
tf.Tensor(16696, shape=(), dtype=int32)
tf.Tensor(16124, shape=(), dtype=int32)
tf.Tensor(13166, shape=(), dtype=int32)
tf.Tensor(12232, shape=(), dtype=int32)
tf.Tensor(11568, shape=(), dtype=int32)
tf.Tensor(11086, shape=(), dtype=int32)
tf.Tensor

In [ ]:
#Filtra todos los estados mayores a 5,000 de personas
dataset = dataset.filter(lambda mexico: mexico > 10000)

In [ ]:
for item in dataset:
    print(item)

tf.Tensor(33984, shape=(), dtype=int32)
tf.Tensor(18418, shape=(), dtype=int32)
tf.Tensor(16696, shape=(), dtype=int32)
tf.Tensor(16124, shape=(), dtype=int32)
tf.Tensor(13166, shape=(), dtype=int32)
tf.Tensor(12232, shape=(), dtype=int32)
tf.Tensor(11568, shape=(), dtype=int32)
tf.Tensor(11086, shape=(), dtype=int32)
tf.Tensor(33984, shape=(), dtype=int32)
tf.Tensor(18418, shape=(), dtype=int32)
tf.Tensor(16696, shape=(), dtype=int32)
tf.Tensor(16124, shape=(), dtype=int32)
tf.Tensor(13166, shape=(), dtype=int32)
tf.Tensor(12232, shape=(), dtype=int32)
tf.Tensor(11568, shape=(), dtype=int32)
tf.Tensor(11086, shape=(), dtype=int32)


In [ ]:
#Usa Take para extraer los primeros 4 estados de tu lista
for item in dataset.take(4):
    print(item)

tf.Tensor(33984, shape=(), dtype=int32)
tf.Tensor(18418, shape=(), dtype=int32)
tf.Tensor(16696, shape=(), dtype=int32)
tf.Tensor(16124, shape=(), dtype=int32)


### <span style="color:blue">1.2 Barajar los Resultados</span>

In [ ]:
#Vuelve a cargar los estados originales, repitelos 3 veces, y barajealos con un buffer de 8 y una semilla de 42, baches de 3
dataset = tf.data.Dataset.from_tensor_slices(Mexico)

In [ ]:
dataset = dataset.repeat(3)

In [ ]:
dataset = dataset.shuffle(buffer_size = 8, seed = 42).batch(3)

In [ ]:
for item in dataset:
    print(item)

tf.Tensor([8062 5543 9209], shape=(3,), dtype=int32)
tf.Tensor([5784 3769 4132], shape=(3,), dtype=int32)
tf.Tensor([8348 4748 3540], shape=(3,), dtype=int32)
tf.Tensor([3082 3741 9209], shape=(3,), dtype=int32)
tf.Tensor([16992 16992  6583], shape=(3,), dtype=int32)
tf.Tensor([6116 3146 3026], shape=(3,), dtype=int32)
tf.Tensor([3527 6583 5543], shape=(3,), dtype=int32)
tf.Tensor([8348 4748 8062], shape=(3,), dtype=int32)
tf.Tensor([4132 3527 3026], shape=(3,), dtype=int32)
tf.Tensor([5784 3741 3146], shape=(3,), dtype=int32)
tf.Tensor([ 3082  9209 16992], shape=(3,), dtype=int32)
tf.Tensor([8062 5543 3769], shape=(3,), dtype=int32)
tf.Tensor([3540 3769 5784], shape=(3,), dtype=int32)
tf.Tensor([4132 8348 4748], shape=(3,), dtype=int32)
tf.Tensor([3741 6116 3146], shape=(3,), dtype=int32)
tf.Tensor([3540 3082 3026], shape=(3,), dtype=int32)
tf.Tensor([3527 6116 6583], shape=(3,), dtype=int32)


### Ahora veamos el ejemplo con el Dataset de casas en California

In [ ]:
# Carga los datos de california, traintestsplit y standardscaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
# Carga los datos de california a variables xtrain y xtest
housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

In [ ]:
# Aplica el scaler y saca mean y std
scaler = StandardScaler()
scaler.fit(X_train)
X_mean = scaler.mean_
X_std = scaler.scale_

In [ ]:
# Vamos a separar el dataset en 20 pequeños archivos CSV - primero definimos una función para esto
def save_to_multiple_csv_files(data,name_prefix, header=None, n_parts = 10):
    housing_dir = os.path.join("datasets","housing")
    os.makedirs(housing_dir, exist_ok=True)
    path_format = os.path.join(housing_dir, "my_{}_{:02d}.csv")

    filepaths = []
    m = len(data)
    for file_idx, row_indices in enumerate(np.array_split(np.arange(m),n_parts)):
        part_csv = path_format.format(name_prefix, file_idx)
        filepaths.append(part_csv)
        with open(part_csv, "wt", encoding="utf-8") as f:
            if header is not None:
                f.write(header)
                f.write("\n")
            for row_idx in row_indices:
                f.write(",".join([repr(col) for col in data[row_idx]]))
                f.write("\n")
    return filepaths


In [ ]:
# Ahora seapramos nuestros datos
train_data = np.c_[X_train,y_train]
valid_data = np.c_[X_valid,y_valid]
test_data = np.c_[X_test,y_test]

In [ ]:
#Preparar los headers
header_cols = housing.feature_names + ["MedianHouseValue"]
header = ",".join(header_cols)

In [ ]:
header

'MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedianHouseValue'

In [ ]:
train_filepaths = save_to_multiple_csv_files(train_data, "train", header, n_parts = 20)
valid_filepaths = save_to_multiple_csv_files(valid_data, "valid", header, n_parts=10)
test_filepaths = save_to_multiple_csv_files(test_data, "test", header, n_parts=10)

In [ ]:
# Veamos el resultado de uno de estos archivos
import pandas as pd
pd.read_csv(train_filepaths[0]).head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  3.5214      15.0  3.049945   1.106548      1447.0  1.605993     37.63   
1  5.3275       5.0  6.490060   0.991054      3464.0  3.443340     33.69   
2  3.1000      29.0  7.542373   1.591525      1328.0  2.250847     38.44   
3  7.1736      12.0  6.289003   0.997442      1054.0  2.695652     33.55   
4  2.0549      13.0  5.312457   1.085092      3297.0  2.244384     33.93   

   Longitude  MedianHouseValue  
0    -122.43             1.442  
1    -117.39             1.687  
2    -122.98             1.621  
3    -117.70             2.621  
4    -116.93             0.956

In [ ]:
# Veamos donde viven estos archivos
train_filepaths

['datasets/housing/my_train_00.csv',
 'datasets/housing/my_train_01.csv',
 'datasets/housing/my_train_02.csv',
 'datasets/housing/my_train_03.csv',
 'datasets/housing/my_train_04.csv',
 'datasets/housing/my_train_05.csv',
 'datasets/housing/my_train_06.csv',
 'datasets/housing/my_train_07.csv',
 'datasets/housing/my_train_08.csv',
 'datasets/housing/my_train_09.csv',
 'datasets/housing/my_train_10.csv',
 'datasets/housing/my_train_11.csv',
 'datasets/housing/my_train_12.csv',
 'datasets/housing/my_train_13.csv',
 'datasets/housing/my_train_14.csv',
 'datasets/housing/my_train_15.csv',
 'datasets/housing/my_train_16.csv',
 'datasets/housing/my_train_17.csv',
 'datasets/housing/my_train_18.csv',
 'datasets/housing/my_train_19.csv']

### <span style="color:blue">1.3 Construyamos un pipeline de ingreso</span>

In [ ]:
# Crea un objeto de filepath dataset
filepath_dataset = tf.data.Dataset.list_files(train_filepaths, seed =42)

In [ ]:
#Checa los contenidos de tu nuevo dataset
for filepath in filepath_dataset:
    print(filepath)

tf.Tensor(b'datasets/housing/my_train_15.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_08.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_03.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_01.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_10.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_05.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_19.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_16.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_02.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_09.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_00.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_07.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_12.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_04.csv', shape=(), dtype=string)
tf.Ten

In [ ]:
#Vamos a leer de 5 archivos al mismo tiempo y mezclar sus lienas (saltandonos las primeras lienas de cada archivo)
n_readers = 5
dataset = filepath_dataset.interleave(lambda filepath: tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers)

In [ ]:
#Checamos resultados
for line in dataset.take(5):
    print(line.numpy())

b'4.6477,38.0,5.03728813559322,0.911864406779661,745.0,2.5254237288135593,32.64,-117.07,1.504'
b'8.72,44.0,6.163179916317992,1.0460251046025104,668.0,2.794979079497908,34.2,-118.18,4.159'
b'3.8456,35.0,5.461346633416459,0.9576059850374065,1154.0,2.8778054862842892,37.96,-122.05,1.598'
b'3.3456,37.0,4.514084507042254,0.9084507042253521,458.0,3.2253521126760565,36.67,-121.7,2.526'
b'3.6875,44.0,4.524475524475524,0.993006993006993,457.0,3.195804195804196,34.04,-118.15,1.625'


In [ ]:
#Hora de aplicar un parse (análisis gramatical) a nuestro dataset, comenzamos con una función que preprocesa nuestros datos:
#1.- Primero tomamos una sola linea del CSV y la parseamos.
#2.- Luego aplicamos tf.stack para amontonar todos nuestros tensores en un arreglo de 1D
#3.- Finalmente, escalamos las variables de entrada y devolvemos una tupla que contiene las variables escaladas y el objetivo

n_inputs = 8
@tf.function

def preprocess(line):
    defs = [0.]*n_inputs + [tf.constant([],dtype=tf.float32)]
    fields = tf.io.decode_csv(line,record_defaults = defs)
    x = tf.stack(fields[:-1])
    y = tf.stack(fields[-1:])
    return(x-X_mean)/X_std,y

In [ ]:
#Ahora aplica la función a una línea para probarla
preprocess(b'4.6477,38.0,5.03728813559322,0.911864406779661,745.0,2.5254237288135593,32.64,-117.07,1.504')

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([ 0.39593136,  0.74167496, -0.16415128, -0.40340805, -0.61991787,
        -0.18355484, -1.4084505 ,  1.2565969 ], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.504], dtype=float32)>)

### <span style="color:blue">1.4 Todo Junto a la Vez</span>

In [ ]:
#Vamos a armar una sola función que haga todo lo que hicimos anteriormente.
#Va a crear y devoler un dataset que cargará los datos de California de varios archivos de CSV, preprocesarlo, barajearlo, y bachearlo.
def csv_reader_dataset(filepaths, repeat = 1, n_readers =5, n_read_threads=None, shuffle_buffer_size = 10000, n_parse_threads = 5, batch_size=32):
    dataset = tf.data.Dataset.list_files(filepaths).repeat(repeat)
    dataset = dataset.interleave(
        lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
        cycle_length=n_readers, num_parallel_calls = n_read_threads)
    dataset = dataset.shuffle(shuffle_buffer_size)
    dataset = dataset.map(preprocess, num_parallel_calls=n_parse_threads)
    dataset = dataset.batch(batch_size)
    return dataset.prefetch(1)

In [ ]:
#Corre tu función sobre nuestra colección de csv, batch size de 3
train_set = csv_reader_dataset(train_filepaths, batch_size = 3)

In [ ]:
#Toma 2 baches y imprime sus valores X y y
for X_batch, y_batch in train_set.take(2):
    print("X = ", X_batch)
    print("y = ", y_batch)
    print()

X =  tf.Tensor(
[[ 1.1832466  -0.2867314   0.256955   -0.0914653   0.6741611   0.05366582
  -0.7432092   0.71184903]
 [-0.44522637  1.8491895  -0.32066625 -0.14044929 -0.10611927 -0.06691425
  -0.691678    0.7318402 ]
 [ 0.3091969   0.5043504   0.20859428 -0.2770272   0.6084533   0.27369827
  -0.84627515  0.7818199 ]], shape=(3, 8), dtype=float32)
y =  tf.Tensor(
[[3.151]
 [2.226]
 [2.141]], shape=(3, 1), dtype=float32)

X =  tf.Tensor(
[[-1.2879554   1.4536486  -0.5052248   0.20396037 -0.49580315  0.43515173
  -0.7666345   0.6568782 ]
 [-0.64608806 -1.0778131  -0.35905546  0.09489206  1.0309911  -0.22977838
  -0.72447133  0.9767287 ]
 [ 1.7620009  -0.6822723   0.7482188  -0.23329605 -0.6326944  -0.32895038
  -1.3241241   1.1716374 ]], shape=(3, 8), dtype=float32)
y =  tf.Tensor(
[[1.141]
 [1.228]
 [3.923]], shape=(3, 1), dtype=float32)



### <span style="color:blue">1.5 Integrar esto en Keras</span>

In [ ]:
#Carga tus datos mediante tu función en 3 sets - training, validación y prueba
train_set = csv_reader_dataset(train_filepaths, repeat=None)
valid_set = csv_reader_dataset(valid_filepaths)
test_set = csv_reader_dataset(test_filepaths)

In [ ]:
#Despeja keras
keras.backend.clear_session()

In [ ]:
#Arma un modelo secuencial de 2 capas densas, 30 neuronas y 1 neurona respectivamente, activacion relu y su figura d eentrada
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1)
])

In [ ]:
#Compila con mse y SGD
model.compile(loss="mse", optimizer=keras.optimizers.SGD(learning_rate=1e-3))

In [ ]:
# Ejecuta en baches de 32, 10 epocas
batch_size = 32
model.fit(train_set, steps_per_epoch = len(X_train)//batch_size, epochs = 10, validation_data = valid_set)

Epoch 1/10
362/362 [==============================] - 3s 7ms/step - loss: 1.9369 - val_loss: 1.1833
Epoch 2/10
362/362 [==============================] - 3s 7ms/step - loss: 0.6851 - val_loss: 1.3781
Epoch 3/10
362/362 [==============================] - 2s 5ms/step - loss: 0.6431 - val_loss: 0.6588
Epoch 4/10
362/362 [==============================] - 1s 3ms/step - loss: 0.6551 - val_loss: 0.5915
Epoch 5/10
362/362 [==============================] - 2s 7ms/step - loss: 0.6097 - val_loss: 0.7647
Epoch 6/10
362/362 [==============================] - 1s 4ms/step - loss: 0.5584 - val_loss: 0.6040
Epoch 7/10
362/362 [==============================] - 1s 4ms/step - loss: 0.5412 - val_loss: 0.6749
Epoch 8/10
362/362 [==============================] - 1s 3ms/step - loss: 0.5223 - val_loss: 0.6188
Epoch 9/10
362/362 [==============================] - 1s 3ms/step - loss: 0.5154 - val_loss: 0.4912
Epoch 10/10
362/362 [==============================] - 1s 3ms/step - loss: 0.5032 - val_loss: 0.5143

In [ ]:
#Evalua el resultado
model.evaluate(test_set, steps=len(X_test) // batch_size)

161/161 [==============================] - 1s 2ms/step - loss: 0.4808


0.4808122515678406

## <span style="color:green">2.Pipeline de Imágenes </span>

In [ ]:
#Guarda la Lista de archivos de tus imágenes
images_ds=tf.data.Dataset.list_files("HotDogs/*/*", shuffle = False)

In [ ]:
#Cuenta la cantidad de imágenes que existen+
for file in images_ds.take(10):
    print(file.numpy())

b'HotDogs/COMIDAS/00.jpg'
b'HotDogs/COMIDAS/09.webp'
b'HotDogs/COMIDAS/10.jpg'
b'HotDogs/COMIDAS/11.jpg'
b'HotDogs/COMIDAS/12.png'
b'HotDogs/COMIDAS/13.webp'
b'HotDogs/COMIDAS/14.webp'
b'HotDogs/COMIDAS/17.jpg'
b'HotDogs/COMIDAS/18.jpg'
b'HotDogs/COMIDAS/19.jpg'


In [ ]:
#Que tipo de dataset es tu archivo
image_count = len(images_ds)
image_count

110

In [ ]:
#Barajea tus imágenes
images_ds = images_ds.shuffle(200)

Enlace HotDogs
[ENLACE](https://universidadsergioarboleda-my.sharepoint.com/:f:/g/personal/joaquin_sanchezc_usa_edu_co/EqHWOMQgzwpGgfbac__4nwkBl9Stgl0xNHPsFl9dm9KtIQ?e=Dkw2cF)

In [ ]:
#Toma 10 imágenes
for file in images_ds.take(10):
    print(file.numpy())

b'HotDogs/COMIDAS/87.jpg'
b'HotDogs/COMIDAS/29.jpeg'
b'HotDogs/COMIDAS/38.jpg'
b'HotDogs/HOTDOGS/hots.webp'
b'HotDogs/COMIDAS/53.jpg'
b'HotDogs/COMIDAS/22.webp'
b'HotDogs/HOTDOGS/p.webp'
b'HotDogs/COMIDAS/26.jpg'
b'HotDogs/COMIDAS/17.jpg'
b'HotDogs/COMIDAS/33.htm'


In [ ]:
#Ármate un set de entrenamiento y un set de prueba (80-20)
train_size = int(image_count*.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [ ]:
#Checa la longitud  de tus sets
len(test_ds)

22

In [ ]:
#Ahora vamos armando una funcion para traer las etiquetas
def get_label(file_path):
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [ ]:
#Vamos probando tu función con una imagen
for file in images_ds.take(10):
    print(get_label(file))

tf.Tensor(b'HOTDOGS', shape=(), dtype=string)
tf.Tensor(b'COMIDAS', shape=(), dtype=string)
tf.Tensor(b'COMIDAS', shape=(), dtype=string)
tf.Tensor(b'COMIDAS', shape=(), dtype=string)
tf.Tensor(b'COMIDAS', shape=(), dtype=string)
tf.Tensor(b'HOTDOGS', shape=(), dtype=string)
tf.Tensor(b'HOTDOGS', shape=(), dtype=string)
tf.Tensor(b'COMIDAS', shape=(), dtype=string)
tf.Tensor(b'HOTDOGS', shape=(), dtype=string)
tf.Tensor(b'COMIDAS', shape=(), dtype=string)


In [ ]:
#Ahora armamos una función para procesar tus imágenes
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpg(img)
    img = tf.image.resize(img, [128,128])
    return img, label

In [ ]:
#COrre tu función y guarda img y etiqueta
img,label = process_image("HotDogs\\COMIDAS\\00.jpg")

In [ ]:
img

<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
array([[[2.52832031e+02, 2.51832031e+02, 2.47832031e+02],
        [2.51437500e+02, 2.50437500e+02, 2.46437500e+02],
        [2.52000000e+02, 2.52000000e+02, 2.50000000e+02],
        ...,
        [1.91591064e+02, 1.48591064e+02, 1.16591064e+02],
        [1.81394531e+02, 1.43394531e+02, 1.07394531e+02],
        [1.84683594e+02, 1.45683594e+02, 1.14683594e+02]],

       [[2.54000000e+02, 2.54000000e+02, 2.52000000e+02],
        [2.52000000e+02, 2.52000000e+02, 2.50000000e+02],
        [2.53000000e+02, 2.52000000e+02, 2.47000000e+02],
        ...,
        [1.95441406e+02, 1.59937500e+02, 1.27937500e+02],
        [1.90496094e+02, 1.54496094e+02, 1.22496094e+02],
        [1.90086670e+02, 1.53086670e+02, 1.25078857e+02]],

       [[2.52809814e+02, 2.52839844e+02, 2.50749756e+02],
        [2.53839844e+02, 2.53749756e+02, 2.55000000e+02],
        [2.54212646e+02, 2.49902344e+02, 2.39187500e+02],
        ...,
        [1.85732178e+02, 1.51732

In [ ]:
#Revisemos el numpy de tu nuevo tensor donde están las imagenes guardadas


In [ ]:
#Set de prueba y set de entrenamiento (mapea estos datos)
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [ ]:
#Revisamos otra imagen en nuestro set de entrenamiento
for image,label in train_ds.take(1):
    print("Image", image)
    print("Label", label)

Image tf.Tensor(
[[[ 11.  14.  65.]
  [ 15.  20.  75.]
  [ 12.  17.  57.]
  ...
  [150. 251. 237.]
  [181. 253. 249.]
  [224. 254. 254.]]

 [[ 16.  19.  72.]
  [ 16.  18.  66.]
  [ 49.  57.  94.]
  ...
  [194. 254. 246.]
  [241. 250. 255.]
  [237. 253. 252.]]

 [[ 13.  17.  65.]
  [ 15.  14.  54.]
  [ 14.  22.  68.]
  ...
  [232. 254. 252.]
  [206. 255. 249.]
  [165. 251. 242.]]

 ...

 [[ 87. 171. 156.]
  [ 87. 171. 156.]
  [ 84. 168. 153.]
  ...
  [165. 223. 173.]
  [166. 225. 179.]
  [171. 228. 185.]]

 [[ 85. 169. 153.]
  [ 75. 159. 144.]
  [ 86. 170. 157.]
  ...
  [180. 236. 187.]
  [172. 229. 186.]
  [164. 229. 197.]]

 [[ 79. 164. 145.]
  [ 85. 169. 154.]
  [ 79. 162. 152.]
  ...
  [177. 233. 184.]
  [171. 226. 186.]
  [158. 227. 206.]]], shape=(128, 128, 3), dtype=float32)
Label tf.Tensor(b'COMIDAS', shape=(), dtype=string)


In [ ]:
#Hay que hacer el scale de la imagen
def scale(image,label):
    return image/255, label

In [ ]:
#Train ds con el scale aplicado
train_ds = train_ds.map(scale)

In [ ]:
#Checamos por óltimo nuestro set de datos con el scale aplicado
for image, label in train_ds.take(1):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.74969363 0.7143995  0.68694854]
****Label:  b'COMIDAS'
